server:
  port: 10010
spring:
  application:
    name: mall-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀h
  routes:
    item-service: /item/** #路由到商品的微服务
